# Generated by Django 4.0.1 on 2022-01-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postcomment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postcomment',
            table='comment',
        ),
    ]
